"""
Django settings for biblio project.

<<<<<<< HEAD
For more information on this file, see
https://docs.djangoproject.com/en/1.7/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.7/ref/settings/
=======
Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
>>>>>>> f7544b077d305be9d45ff1551ad65dd9172111dd
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
<<<<<<< HEAD
BASE_DIR = os.path.dirname(os.path.dirname(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.7/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^m7oevi@s!yveglv)a4plj*tl54!$l_9lnqd!q8ahju!5w7nz%'
=======

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'v-zcruwu@3^%54tn1np#f(+=!$rmgarx(ohkpr85328i7=j56u'
>>>>>>> f7544b077d305be9d45ff1551ad65dd9172111dd

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

<<<<<<< HEAD
TEMPLATE_DEBUG = True

=======
>>>>>>> f7544b077d305be9d45ff1551ad65dd9172111dd
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
    'shelf',
=======
>>>>>>> f7544b077d305be9d45ff1551ad65dd9172111dd
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
<<<<<<< HEAD
=======
    'django.middleware.security.SecurityMiddleware',
>>>>>>> f7544b077d305be9d45ff1551ad65dd9172111dd
)

ROOT_URLCONF = 'biblio.urls'

<<<<<<< HEAD
=======
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

>>>>>>> f7544b077d305be9d45ff1551ad65dd9172111dd
WSGI_APPLICATION = 'biblio.wsgi.application'


# Database
<<<<<<< HEAD
# https://docs.djangoproject.com/en/1.7/ref/settings/#databases
=======
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
>>>>>>> f7544b077d305be9d45ff1551ad65dd9172111dd

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

<<<<<<< HEAD
# Internationalization
# https://docs.djangoproject.com/en/1.7/topics/i18n/

LANGUAGE_CODE = 'pl'

TIME_ZONE = 'UTC'
=======

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'pl'

TIME_ZONE = 'Europe/Warsaw'
>>>>>>> f7544b077d305be9d45ff1551ad65dd9172111dd

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
<<<<<<< HEAD
# https://docs.djangoproject.com/en/1.7/howto/static-files/

STATIC_URL = '/static/'

TEMPLATE_DIRS = {
    os.path.join(BASE_DIR, 'templates'),
}
=======
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
>>>>>>> f7544b077d305be9d45ff1551ad65dd9172111dd
